// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module reduce_ap_ufixed_4_Op_max_ap_ufixed_6_0_0_0_0_s (
        ap_ready,
        x_0_V_read,
        x_1_V_read,
        x_2_V_read,
        x_3_V_read,
        ap_return
);


output   ap_ready;
input  [5:0] x_0_V_read;
input  [5:0] x_1_V_read;
input  [5:0] x_2_V_read;
input  [5:0] x_3_V_read;
output  [5:0] ap_return;

wire   [0:0] icmp_ln1496_fu_34_p2;
wire   [0:0] icmp_ln1496_1_fu_48_p2;
wire   [5:0] select_ln86_fu_40_p3;
wire   [5:0] select_ln86_1_fu_54_p3;
wire   [0:0] icmp_ln1496_2_fu_62_p2;

assign ap_ready = 1'b1;

assign ap_return = ((icmp_ln1496_2_fu_62_p2[0:0] === 1'b1) ? select_ln86_1_fu_54_p3 : select_ln86_fu_40_p3);

assign icmp_ln1496_1_fu_48_p2 = ((x_2_V_read < x_3_V_read) ? 1'b1 : 1'b0);

assign icmp_ln1496_2_fu_62_p2 = ((select_ln86_fu_40_p3 < select_ln86_1_fu_54_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_fu_34_p2 = ((x_0_V_read < x_1_V_read) ? 1'b1 : 1'b0);

assign select_ln86_1_fu_54_p3 = ((icmp_ln1496_1_fu_48_p2[0:0] === 1'b1) ? x_3_V_read : x_2_V_read);

assign select_ln86_fu_40_p3 = ((icmp_ln1496_fu_34_p2[0:0] === 1'b1) ? x_1_V_read : x_0_V_read);

endmodule //reduce_ap_ufixed_4_Op_max_ap_ufixed_6_0_0_0_0_s
