// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _reduce_ap_ufixed_4_Op_max_ap_ufixed_6_0_0_0_0_s_HH_
#define _reduce_ap_ufixed_4_Op_max_ap_ufixed_6_0_0_0_0_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct reduce_ap_ufixed_4_Op_max_ap_ufixed_6_0_0_0_0_s : public sc_module {
    // Port declarations 6
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<6> > x_0_V_read;
    sc_in< sc_lv<6> > x_1_V_read;
    sc_in< sc_lv<6> > x_2_V_read;
    sc_in< sc_lv<6> > x_3_V_read;
    sc_out< sc_lv<6> > ap_return;


    // Module declarations
    reduce_ap_ufixed_4_Op_max_ap_ufixed_6_0_0_0_0_s(sc_module_name name);
    SC_HAS_PROCESS(reduce_ap_ufixed_4_Op_max_ap_ufixed_6_0_0_0_0_s);

    ~reduce_ap_ufixed_4_Op_max_ap_ufixed_6_0_0_0_0_s();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > icmp_ln1496_fu_34_p2;
    sc_signal< sc_lv<1> > icmp_ln1496_1_fu_48_p2;
    sc_signal< sc_lv<6> > select_ln86_fu_40_p3;
    sc_signal< sc_lv<6> > select_ln86_1_fu_54_p3;
    sc_signal< sc_lv<1> > icmp_ln1496_2_fu_62_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return();
    void thread_icmp_ln1496_1_fu_48_p2();
    void thread_icmp_ln1496_2_fu_62_p2();
    void thread_icmp_ln1496_fu_34_p2();
    void thread_select_ln86_1_fu_54_p3();
    void thread_select_ln86_fu_40_p3();
};

}

using namespace ap_rtl;

#endif
