-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reduce_ap_ufixed_4_Op_max_ap_ufixed_6_0_0_0_0_s is
port (
    ap_ready : OUT STD_LOGIC;
    x_0_V_read : IN STD_LOGIC_VECTOR (5 downto 0);
    x_1_V_read : IN STD_LOGIC_VECTOR (5 downto 0);
    x_2_V_read : IN STD_LOGIC_VECTOR (5 downto 0);
    x_3_V_read : IN STD_LOGIC_VECTOR (5 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of reduce_ap_ufixed_4_Op_max_ap_ufixed_6_0_0_0_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal icmp_ln1496_fu_34_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_1_fu_48_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_fu_40_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln86_1_fu_54_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln1496_2_fu_62_p2 : STD_LOGIC_VECTOR (0 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        select_ln86_1_fu_54_p3 when (icmp_ln1496_2_fu_62_p2(0) = '1') else 
        select_ln86_fu_40_p3;
    icmp_ln1496_1_fu_48_p2 <= "1" when (unsigned(x_2_V_read) < unsigned(x_3_V_read)) else "0";
    icmp_ln1496_2_fu_62_p2 <= "1" when (unsigned(select_ln86_fu_40_p3) < unsigned(select_ln86_1_fu_54_p3)) else "0";
    icmp_ln1496_fu_34_p2 <= "1" when (unsigned(x_0_V_read) < unsigned(x_1_V_read)) else "0";
    select_ln86_1_fu_54_p3 <= 
        x_3_V_read when (icmp_ln1496_1_fu_48_p2(0) = '1') else 
        x_2_V_read;
    select_ln86_fu_40_p3 <= 
        x_1_V_read when (icmp_ln1496_fu_34_p2(0) = '1') else 
        x_0_V_read;
end behav;
